# 4) შექმენით სიები fruits, colors, numbers. თითოეულზე გამოიყენეთ index, count, sort, sorted, min, max მეთოდები & ფუნქციები და დააკომენტარეთ თითოეული მაგალითი (რას აკეთებს)
fruits = ['apple', 'banana', 'cherry', 'date', 'elderberry']    
colors = ['red', 'blue', 'green', 'yellow', 'purple']
numbers = [5, 3, 8, 1, 4]
fruit_index = fruits.index('cherry')
fruit_count = fruits.count('apple')
fruits.sort()
sorted_fruits = sorted(fruits)
min_fruit = min(fruits)
max_fruit = max(fruits)
color_index = colors.index('green')
color_count = colors.count('red')
colors.sort()
sorted_colors = sorted(colors)
min_color = min(colors)
max_color = max(colors)
number_index = numbers.index(8)
number_count = numbers.count(3)
numbers.sort()
sorted_numbers = sorted(numbers)
min_number = min(numbers)
max_number = max(numbers)
